#ifndef INC_FLOATSAT_INIT_H
#define INC_FLOATSAT_INIT_H

#include "stm32f4xx_hal.h"

#include "floatsat_error.h"

#include "LSM9DS1_stm32.h"
#include "madgwick_filter.h"
#include "floatsat_telecommand.h"
#include "floatsat_telemetry.h"
#include "floatsat_control.h"
#include "floatsat_core.h"
#include "floatsat_motor_controller.h"

// Structure to enclose all peripheral handles. This is required to cleanly
// pass all the handles from main.c to floatsat_init.c
typedef struct floatsat_periph_t {
    I2C_HandleTypeDef       *imu_i2c;
    UART_HandleTypeDef      *main_uart;
    TIM_HandleTypeDef       *motor_pwm_timer;
    TIM_HandleTypeDef       *encoder_timer;
    TIM_HandleTypeDef       *encoder_sampling_timer;


}floatsat_periph_t;


// Structure to pass user constants generated by the CubeMX in main.h to the
// floatsat_init module
typedef struct mx_user_constants_t {
    uint32_t encoder_sampling_period_ms;
    
}mx_user_constants_t;


// Strcuture to pass callbacks from floatsat_init to main.c
typedef struct floatsat_callbacks_t {
    void        (*encoder_sample_cb)(TIM_HandleTypeDef *tim);
}floatsat_callbacks_t;

// Structure to group all task handles. This is required to cleanly pass all 
/// handles from main.c to floatsat_init.c
typedef struct floatsat_tasks_t {
    TaskHandle_t    cmd_manager_task;
    TaskHandle_t    telemetry_task;
}floatsat_tasks_t;

// Struct to group all initialized handles so they can be passed as parameters to
// the FreeRTOS tasks
typedef struct floatsat_handles_t {
    const cmd_manager_handle_t    *cmd_manager_handle;
    const telemetry_handle_t      *telemetry_handle;
    const control_handle_t        *control_handle;
    const madgwick_filter_t       *madgwick_filter;
    const floatsat_core_t         *core_handle;
}floatsat_handles_t;


floatsat_err_t FloatSat_Init(const floatsat_periph_t *periph, 
                             const mx_user_constants_t *constants, 
                             floatsat_callbacks_t *out_callbacks);
const floatsat_handles_t*  FloatSat_GetHandles(void);


#endif
