/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     Implementación de memoria dinámica requerida por Newlib.
 *
 * Este archivo proporciona la función de bajo nivel _sbrk(), utilizada
 * por la biblioteca estándar de C para ampliar el área de memoria conocida
 * como heap.
 *
 * Funciones como las siguientes pueden terminar utilizando _sbrk():
 *
 *   malloc()
 *   calloc()
 *   realloc()
 *   algunas operaciones internas de printf()
 *
 * En el STM32 no existe un sistema operativo que entregue memoria dinámica.
 * Por ello, _sbrk() administra manualmente una región de RAM comprendida
 * entre el final de las variables estáticas y la zona reservada para la pila
 * principal MSP.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/* Includes ------------------------------------------------------------------*/

/*
 * Declara:
 *
 *   errno
 *   ENOMEM
 *
 * ENOMEM significa que no hay memoria suficiente para completar
 * una solicitud.
 */
#include <errno.h>

/*
 * Declara tipos enteros de tamaño fijo:
 *
 *   uint8_t
 *   uint32_t
 */
#include <stdint.h>


/* Variables -----------------------------------------------------------------*/

/**
 * @brief Dirección actual del final del heap administrado por Newlib.
 *
 * Esta variable funciona como un marcador de agua alta:
 *
 *   - Inicialmente vale NULL.
 *   - En la primera llamada se coloca en &_end.
 *   - Cada solicitud positiva incrementa esta dirección.
 *
 * La variable es static, por lo que solamente puede utilizarse dentro
 * de este archivo.
 */
static uint8_t *__sbrk_heap_end = NULL;


/**
 * @brief Aumenta o reduce el área de heap disponible para Newlib.
 *
 * _sbrk() es una función de bajo nivel utilizada por malloc() y otras
 * funciones de la biblioteca estándar de C.
 *
 * Distribución conceptual de la RAM:
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         # Reserved by _Min_Stack_Size #
 * ############################################################################
 * ^-- RAM start      ^-- _end                             _estack, RAM end --^
 * @endverbatim
 *
 * Las regiones principales son:
 *
 *   .data
 *     Variables globales y estáticas inicializadas.
 *
 *   .bss
 *     Variables globales y estáticas inicializadas en cero.
 *
 *   _end
 *     Símbolo del linker que marca el final de .data y .bss.
 *     Desde aquí comienza el heap de Newlib.
 *
 *   newlib heap
 *     Región que puede crecer mediante _sbrk().
 *
 *   MSP stack
 *     Espacio reservado para la pila principal del procesador.
 *
 *   _estack
 *     Dirección superior de la RAM y valor inicial del MSP.
 *
 *   _Min_Stack_Size
 *     Cantidad mínima de RAM reservada para la pila MSP.
 *
 * El heap crece desde direcciones bajas hacia direcciones altas.
 * La pila MSP normalmente crece desde direcciones altas hacia direcciones
 * bajas. Esta función intenta evitar que ambas regiones se superpongan.
 *
 * @param incr Número de bytes que se desea mover el final del heap.
 *
 *             Si incr es positivo, el heap aumenta.
 *             Si incr es negativo, el heap disminuye.
 *
 * @return Dirección inicial del bloque recién reservado.
 *
 * @return (void *)-1 si no existe memoria suficiente.
 */
void *_sbrk(ptrdiff_t incr)
{
  /*
   * Símbolo definido en el linker script.
   *
   * Representa la primera dirección disponible después de las secciones:
   *
   *   .data
   *   .bss
   *
   * No es una variable normal almacenada en RAM. Su dirección representa
   * directamente el valor calculado por el linker.
   */
  extern uint8_t _end;


  /*
   * Símbolo definido en el linker script.
   *
   * Representa el extremo superior de la RAM y normalmente el valor inicial
   * cargado en el Main Stack Pointer, MSP, después del reset.
   */
  extern uint8_t _estack;


  /*
   * Símbolo absoluto definido en el linker script.
   *
   * Su dirección se interpreta como el tamaño reservado para la pila MSP.
   *
   * Por ejemplo, si en el linker script aparece:
   *
   *   _Min_Stack_Size = 0x400;
   *
   * entonces:
   *
   *   (uint32_t)&_Min_Stack_Size
   *
   * produce el valor 0x400, equivalente a 1024 bytes.
   */
  extern uint32_t _Min_Stack_Size;


  /*
   * Calcular la dirección inferior de la zona reservada para el MSP:
   *
   *   límite_pila = final_RAM - tamaño_reservado_MSP
   *
   * Ejemplo:
   *
   *   _estack          = 0x20020000
   *   _Min_Stack_Size  = 0x00000400
   *
   *   stack_limit      = 0x2001FC00
   *
   * El heap no debe superar esta dirección.
   */
  const uint32_t stack_limit =
      (uint32_t)&_estack -
      (uint32_t)&_Min_Stack_Size;


  /*
   * Convertir el límite calculado a puntero para compararlo con
   * __sbrk_heap_end.
   */
  const uint8_t *max_heap =
      (uint8_t *)stack_limit;


  /*
   * Guardará la posición anterior del final del heap.
   *
   * Esa dirección será devuelta como inicio del nuevo bloque reservado.
   */
  uint8_t *prev_heap_end;


  /* ------------------------------------------------------------------------ */
  /* Inicialización del heap                                                  */
  /* ------------------------------------------------------------------------ */

  /*
   * Durante la primera llamada todavía no existe una posición de heap
   * registrada.
   */
  if (NULL == __sbrk_heap_end)
  {
    /*
     * Comenzar el heap inmediatamente después de las variables
     * globales y estáticas.
     */
    __sbrk_heap_end = &_end;
  }


  /* ------------------------------------------------------------------------ */
  /* Comprobación de espacio disponible                                       */
  /* ------------------------------------------------------------------------ */

  /*
   * Calcular cuál sería el nuevo final del heap:
   *
   *   nuevo_final = final_actual + incremento
   *
   * Si supera max_heap, la nueva región invadiría la zona reservada
   * para la pila MSP.
   */
  if (__sbrk_heap_end + incr > max_heap)
  {
    /*
     * Informar a Newlib que no existe memoria suficiente.
     */
    errno = ENOMEM;

    /*
     * El valor convencional de error para sbrk() es:
     *
     *   (void *)-1
     *
     * No debe confundirse con NULL.
     */
    return (void *)-1;
  }


  /* ------------------------------------------------------------------------ */
  /* Actualización del final del heap                                         */
  /* ------------------------------------------------------------------------ */

  /*
   * Guardar la dirección inicial del nuevo bloque.
   */
  prev_heap_end = __sbrk_heap_end;


  /*
   * Desplazar el final del heap la cantidad solicitada.
   *
   * Para incr positivo:
   *
   *   el heap crece.
   *
   * Para incr negativo:
   *
   *   el heap disminuye.
   */
  __sbrk_heap_end += incr;


  /*
   * Devolver la posición anterior.
   *
   * Para una solicitud de N bytes:
   *
   *   bloque entregado:
   *       [prev_heap_end, prev_heap_end + N)
   *
   *   nuevo final:
   *       prev_heap_end + N
   */
  return (void *)prev_heap_end;
}
