/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     Implementación mínima de llamadas al sistema para Newlib.
 *
 * En un sistema operativo convencional, funciones como printf(), scanf(),
 * malloc(), fopen() o exit() terminan solicitando servicios al sistema
 * operativo.
 *
 * El STM32 no dispone de un sistema operativo POSIX ni de archivos,
 * procesos o terminales reales. Por eso Newlib necesita estas funciones
 * mínimas para enlazar correctamente la biblioteca estándar de C.
 *
 * Las funciones más relevantes para este proyecto son:
 *
 *   _write() -> permite redirigir printf().
 *   _read()  -> permite redirigir scanf() y otras lecturas estándar.
 *   _exit()  -> comportamiento cuando el programa intenta terminar.
 *
 * Las demás funciones simulan servicios inexistentes o informan error.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/* Includes ------------------------------------------------------------------*/

/*
 * Define struct stat y constantes asociadas a información de archivos,
 * como S_IFCHR.
 */
#include <sys/stat.h>

/*
 * Proporciona funciones y tipos generales de la biblioteca estándar,
 * como malloc(), free() y exit().
 *
 * No todas se utilizan directamente en este archivo, pero forman parte
 * de la plantilla generada para Newlib.
 */
#include <stdlib.h>

/*
 * Declara errno y códigos de error como:
 *
 *   EINVAL
 *   ECHILD
 *   ENOENT
 *   EMLINK
 *   EAGAIN
 *   ENOMEM
 */
#include <errno.h>

/*
 * Declara funciones de entrada y salida estándar:
 *
 *   printf()
 *   scanf()
 *   FILE
 *   stdin, stdout y stderr
 */
#include <stdio.h>

/*
 * Define tipos y constantes relacionados con señales.
 *
 * Se incluye como parte de la compatibilidad básica de Newlib,
 * aunque el STM32 no ejecuta señales POSIX reales.
 */
#include <signal.h>

/*
 * Declara tipos y funciones relacionadas con fecha y tiempo,
 * como time_t.
 */
#include <time.h>

/*
 * Declara estructuras de tiempo utilizadas por determinadas funciones
 * del entorno POSIX.
 */
#include <sys/time.h>

/*
 * Declara struct tms, utilizado por _times().
 */
#include <sys/times.h>


/* Variables -----------------------------------------------------------------*/

/*
 * Función de salida de un carácter.
 *
 * El atributo weak significa que puede existir sin una implementación
 * fuerte dentro de este archivo. Otro módulo puede proporcionar una función
 * con el mismo nombre para redirigir los caracteres hacia:
 *
 *   - USART1.
 *   - SWO.
 *   - USB CDC.
 *   - Otra interfaz.
 *
 * Ejemplo típico:
 *
 *   int __io_putchar(int ch)
 *   {
 *       HAL_UART_Transmit(&huart1, (uint8_t *)&ch, 1U, 100U);
 *       return ch;
 *   }
 */
extern int __io_putchar(int ch) __attribute__((weak));


/*
 * Función de entrada de un carácter.
 *
 * También es weak para permitir una implementación personalizada,
 * normalmente mediante UART.
 */
extern int __io_getchar(void) __attribute__((weak));


/*
 * Entorno mínimo del proceso.
 *
 * En sistemas POSIX, environ contiene variables de entorno como:
 *
 *   PATH
 *   HOME
 *   LANG
 *
 * En el STM32 no existen variables de entorno reales. Se crea un arreglo
 * con un único puntero nulo para satisfacer a la biblioteca estándar.
 */
char *__env[1] = { 0 };

/*
 * Puntero global esperado por ciertas funciones de la biblioteca C.
 *
 * Apunta al entorno vacío definido anteriormente.
 */
char **environ = __env;


/* Functions -----------------------------------------------------------------*/

/**
 * @brief Inicializa los manejadores del monitor de depuración.
 *
 * Esta función suele utilizarse en proyectos con semihosting.
 * En esta implementación está vacía porque no se configura ningún monitor.
 *
 * La forma antigua sin "(void)" significa en C que los parámetros no están
 * especificados. Una declaración más explícita sería:
 *
 *   void initialise_monitor_handles(void)
 */
void initialise_monitor_handles()
{
}


/**
 * @brief Devuelve un identificador de proceso ficticio.
 *
 * Un STM32 bare-metal no posee procesos POSIX. Se devuelve siempre 1 para
 * satisfacer las funciones de Newlib que esperan un PID válido.
 *
 * @return Identificador ficticio del único programa en ejecución.
 */
int _getpid(void)
{
  return 1;
}


/**
 * @brief Simula el envío de una señal a un proceso.
 *
 * El STM32 no implementa procesos ni señales POSIX, por lo que la operación
 * siempre falla.
 *
 * @param pid Identificador del proceso solicitado.
 * @param sig Señal solicitada.
 *
 * @return -1 para indicar error.
 */
int _kill(int pid, int sig)
{
  /*
   * Evitar advertencias del compilador por parámetros no utilizados.
   */
  (void)pid;
  (void)sig;

  /*
   * EINVAL indica que el argumento o la operación no son válidos.
   */
  errno = EINVAL;

  return -1;
}


/**
 * @brief Finaliza la aplicación.
 *
 * En un sistema operativo, _exit() devolvería el control al sistema.
 * En un microcontrolador no existe un sistema al cual regresar.
 *
 * La implementación:
 *
 *   1. Llama a _kill() para registrar un error.
 *   2. Entra permanentemente en un bucle infinito.
 *
 * @param status Código de salida solicitado por la aplicación.
 */
void _exit(int status)
{
  /*
   * Utiliza status como identificador ficticio y -1 como señal.
   *
   * _kill() siempre asignará errno = EINVAL y devolverá -1.
   */
  _kill(status, -1);

  /*
   * Impedir que la ejecución continúe después de exit().
   */
  while (1)
  {
  }
}


/**
 * @brief Implementación mínima de lectura para Newlib.
 *
 * Puede ser utilizada internamente por:
 *
 *   - scanf().
 *   - getchar().
 *   - fread() sobre stdin.
 *
 * Se intenta leer exactamente len caracteres mediante __io_getchar().
 *
 * El atributo weak permite reemplazar toda la función _read() desde otro
 * archivo por una implementación más apropiada.
 *
 * @param file Descriptor de archivo.
 *             Normalmente 0 representa stdin.
 * @param ptr  Buffer donde se guardarán los caracteres recibidos.
 * @param len  Cantidad de caracteres solicitados.
 *
 * @return Cantidad de caracteres leídos.
 */
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  /*
   * Esta implementación ignora el descriptor.
   *
   * Tratará igual stdin y cualquier otro valor.
   */
  (void)file;

  /*
   * Índice del carácter que se está leyendo.
   */
  int DataIdx;

  /*
   * Leer exactamente len caracteres.
   *
   * ptr++ guarda el carácter en la posición actual y después avanza
   * el puntero a la siguiente posición.
   */
  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  /*
   * Se informa que se leyeron todos los caracteres solicitados.
   */
  return len;
}


/**
 * @brief Implementación mínima de escritura para Newlib.
 *
 * Puede ser utilizada internamente por:
 *
 *   - printf().
 *   - puts().
 *   - putchar().
 *   - fwrite() sobre stdout o stderr.
 *
 * Cada carácter se entrega individualmente a __io_putchar().
 *
 * El atributo weak permite reemplazar toda la función desde otro módulo.
 *
 * @param file Descriptor de archivo.
 *             Normalmente 1 representa stdout y 2 representa stderr.
 * @param ptr  Buffer que contiene los datos que se transmitirán.
 * @param len  Cantidad de caracteres que se transmitirán.
 *
 * @return Cantidad de caracteres informados como escritos.
 */
__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  /*
   * La implementación no distingue entre stdout, stderr u otros
   * descriptores.
   */
  (void)file;

  /*
   * Índice del carácter que se está transmitiendo.
   */
  int DataIdx;

  /*
   * Transmitir cada carácter individualmente.
   */
  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }

  /*
   * Se informa que se escribieron todos los caracteres, aunque
   * __io_putchar() no haya sido comprobado.
   */
  return len;
}


/**
 * @brief Simula el cierre de un archivo.
 *
 * El sistema no dispone de archivos abiertos, por lo que siempre falla.
 *
 * @param file Descriptor solicitado.
 *
 * @return -1 para indicar error.
 */
int _close(int file)
{
  (void)file;

  return -1;
}


/**
 * @brief Devuelve información mínima sobre un descriptor.
 *
 * Todos los descriptores se presentan como dispositivos de caracteres,
 * equivalentes conceptualmente a una terminal o puerto serial.
 *
 * @param file Descriptor consultado.
 * @param st   Estructura donde se escribirá la información.
 *
 * @return 0 para indicar que la operación fue completada.
 */
int _fstat(int file, struct stat *st)
{
  (void)file;

  /*
   * S_IFCHR indica que el descriptor se comporta como dispositivo
   * orientado a caracteres.
   */
  st->st_mode = S_IFCHR;

  return 0;
}


/**
 * @brief Indica si un descriptor representa una terminal.
 *
 * La función devuelve siempre verdadero para que stdout y stdin sean
 * tratados como dispositivos interactivos.
 *
 * @param file Descriptor consultado.
 *
 * @return 1, indicando comportamiento de terminal.
 */
int _isatty(int file)
{
  (void)file;

  return 1;
}


/**
 * @brief Simula el desplazamiento dentro de un archivo.
 *
 * No existe almacenamiento con posición de lectura, por lo que los
 * parámetros se ignoran y se devuelve cero.
 *
 * @param file Descriptor solicitado.
 * @param ptr  Desplazamiento solicitado.
 * @param dir  Punto de referencia del desplazamiento.
 *
 * @return 0.
 */
int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;

  return 0;
}


/**
 * @brief Simula la apertura de un archivo.
 *
 * El sistema no dispone de sistema de archivos, por lo que siempre falla.
 *
 * Los puntos suspensivos representan argumentos opcionales, como permisos
 * de creación, que podrían acompañar a open() en un sistema POSIX.
 *
 * @param path  Ruta solicitada.
 * @param flags Modo de apertura.
 *
 * @return -1 para indicar error.
 */
int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;

  /*
   * Simular que cualquier intento de apertura falla.
   */
  return -1;
}


/**
 * @brief Simula la espera de finalización de un proceso hijo.
 *
 * El STM32 no dispone de procesos hijos.
 *
 * @param status Puntero donde normalmente se escribiría el estado
 *               del proceso finalizado.
 *
 * @return -1 para indicar error.
 */
int _wait(int *status)
{
  (void)status;

  /*
   * ECHILD indica que no existen procesos hijos.
   */
  errno = ECHILD;

  return -1;
}


/**
 * @brief Simula la eliminación de un archivo.
 *
 * No existe sistema de archivos, por lo que la operación siempre falla.
 *
 * @param name Nombre del archivo solicitado.
 *
 * @return -1 para indicar error.
 */
int _unlink(char *name)
{
  (void)name;

  /*
   * ENOENT indica que el archivo o ruta no existe.
   */
  errno = ENOENT;

  return -1;
}


/**
 * @brief Intenta obtener estadísticas de tiempo del proceso.
 *
 * No hay medición de tiempo de procesos en esta implementación.
 *
 * @param buf Estructura donde deberían guardarse los tiempos.
 *
 * @return -1 para indicar que no está implementado.
 */
int _times(struct tms *buf)
{
  (void)buf;

  return -1;
}


/**
 * @brief Devuelve información mínima sobre una ruta.
 *
 * Igual que _fstat(), presenta cualquier nombre como un dispositivo
 * orientado a caracteres.
 *
 * @param file Nombre o ruta consultada.
 * @param st   Estructura donde se escribirá el tipo.
 *
 * @return 0.
 */
int _stat(char *file, struct stat *st)
{
  (void)file;

  st->st_mode = S_IFCHR;

  return 0;
}


/**
 * @brief Simula la creación de un enlace entre archivos.
 *
 * El sistema no posee sistema de archivos ni enlaces.
 *
 * @param old Nombre original.
 * @param new Nombre del enlace.
 *
 * @return -1 para indicar error.
 */
int _link(char *old, char *new)
{
  (void)old;
  (void)new;

  /*
   * EMLINK indica demasiados enlaces o imposibilidad de crear el enlace.
   */
  errno = EMLINK;

  return -1;
}


/**
 * @brief Simula la creación de un proceso hijo.
 *
 * El STM32 no implementa procesos POSIX.
 *
 * @return -1 para indicar error.
 */
int _fork(void)
{
  /*
   * EAGAIN indica que el recurso o proceso no pudo crearse.
   */
  errno = EAGAIN;

  return -1;
}


/**
 * @brief Simula la ejecución de otro programa.
 *
 * El firmware no dispone de un cargador de procesos ni de ejecutables
 * externos.
 *
 * @param name Nombre del ejecutable.
 * @param argv Lista de argumentos.
 * @param env  Variables de entorno.
 *
 * @return -1 para indicar error.
 */
int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;

  /*
   * ENOMEM se utiliza para indicar que la operación no pudo realizarse.
   */
  errno = ENOMEM;

  return -1;
}
